# Generated by Django 4.2 on 2024-09-07 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='clubhouse',
            field=models.IntegerField(),
        ),
    ]
